name: Deploy infrastructure
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
patents:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-west-2
    steps:
      - uses: actions/checkout@v3
      - name: setup backend s3 buckets and make zipfile for lambda function
        run:  |
          sh upload_source.sh
      - name: run terraform
        run:  |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
