name: Deploy infrastructure
on:
  push:
    branches:
      - main
      - patent-ci/cd
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      PATENT_API_KEY: ${{ secrets.PATENT_API_KEY }}
      PATENT_CSRFTOKEN: ${{ secrets.PATENT_CSRFTOKEN }}
      SNS: ${{ secrets.SNS_EMAIL }}
      AWS_REGION: us-west-2
    steps:
      - uses: actions/checkout@v3
      - name: setup backend s3 buckets and make zipfile for lambda function
        run:  |
          sh upload_source.sh
      - name: run terraform
        run:  |
          cd infrastructure
          terraform init -backend-config=config.s3.tfbackend
          terraform apply -auto-approve
      - name: configure test event and invoke lambda function
        run:  |
          sh lambda_invoke.sh
          
